apiVersion: batch/v1
kind: Job
metadata:
  name: crud-migration-job
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
        - name: crud-service
          # ARM image
#          image: ogara/otus-microservice:hw2-arm
          # AMD image
          image: ogara/otus-microservice:hw2-amd
          command: ["php",  "/app/migration.php"]
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: crud-configmap
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: crud-configmap
                  key: DB_PORT
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: crud-configmap
                  key: DB_NAME
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: crud-configmap
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  #                  the secret auto created by helm db install
                  name: crud-db-mariadb
                  key: mariadb-password
      restartPolicy: Never