apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helm-version.fullname" . }}-configmap
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
data:
  DB_HOST: {{ .Values.db.dbhost | quote }}
  DB_PORT: {{ .Values.db.dbport | quote }}
  DB_NAME: {{ .Values.db.dbname | quote }}
  DB_USERNAME: {{ .Values.db.dbusername | quote }}