apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "helm-version.fullname" . }}-ingress
#  annotations:
#    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.ingress.host}}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "helm-version.fullname" . }}-service
                port:
                  number: {{ .Values.deployment.port }}
                