apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "helm-version.fullname" . }}-migration-job
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
        - name: {{ include "helm-version.fullname" . }}-migration-job
          # ARM image
          image: {{ .Values.deployment.image }}
          command: ["php",  "/app/migration.php"]
          env:
{{ include "crudchart.dbenvs" . | indent 12}}
      restartPolicy: Never