apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-version.fullname" . }}-service
spec:
  selector:
    app: {{ include "helm-version.fullname" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.deployment.port }}
      targetPort: web
  type: ClusterIP
  