{
 "title": "Otus HM Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Latency Percentile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "avg(http_server_requests_seconds{quantile=\"0.5\"})",
     "legendFormat": "q0.5"
    },
    {
     "expr": "avg(http_server_requests_seconds{quantile=\"0.95\"})",
     "legendFormat": "q0.95"
    },
    {
     "expr": "avg(http_server_requests_seconds{quantile=\"0.99\"})",
     "legendFormat": "q0.99"
    },
    {
     "expr": "avg(http_server_requests_seconds{quantile=\"1.0\"})",
     "legendFormat": "qmax"
    }
   ]
  },
  {
   "title": "RPS Per Method",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{method=\"GET\"}[1m]))",
     "legendFormat": "GET"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{method=\"POST\"}[1m]))",
     "legendFormat": "POST"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{method=\"PUT\"}[1m]))",
     "legendFormat": "PUT"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{method=\"DELETE\"}[1m]))",
     "legendFormat": "DELETE"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{status=~\"4..\"}[1m]))",
     "legendFormat": "400 errors"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{status=~\"5..\"}[1m]))",
     "legendFormat": "500 errors"
    }
   ]
  },
  { "title": "Ingress", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Latency Ingress",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "avg(histogram_quantile(1, rate(nginx_ingress_controller_request_duration_seconds_bucket[1m])))",
     "legendFormat": "qmax"
    },
    {
     "expr": "avg(histogram_quantile(0.5, rate(nginx_ingress_controller_request_duration_seconds_bucket[1m])))",
     "legendFormat": "q0.5"
    },
    {
     "expr": "avg(histogram_quantile(0.95, rate(nginx_ingress_controller_request_duration_seconds_bucket[1m])))",
     "legendFormat": "q0.95"
    },
    {
     "expr": "avg(histogram_quantile(0.99, rate(nginx_ingress_controller_request_duration_seconds_bucket[1m])))",
     "legendFormat": "q0.99"
    }
   ]
  },
  {
   "title": "RPS ingress",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_request_size_count[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors Ingress",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_request_size_count{status=~\"4..\"}[1m]))",
     "legendFormat": "4xx errors"
    },
    {
     "expr": "sum(rate(nginx_ingress_controller_request_size_count{status=~\"5..\"}[1m]))",
     "legendFormat": "5xx errors"
    }
   ]
  },
  {
   "title": "Playgrround",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "Latency (response time)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_sum{method=\"GET\"}[1m]))/sum(rate(http_server_requests_seconds_count{method=\"GET\"}[1m]))",
       "legendFormat": "GET"
      },
      {
       "expr": "sum(rate(http_server_requests_seconds_sum{method=\"POST\"}[1m]))/sum(rate(http_server_requests_seconds_count{method=\"POST\"}[1m]))",
       "legendFormat": "POST"
      },
      {
       "expr": "sum(rate(http_server_requests_seconds_sum{method=\"PUT\"}[1m]))/sum(rate(http_server_requests_seconds_count{method=\"PUT\"}[1m]))",
       "legendFormat": "PUT"
      },
      {
       "expr": "sum(rate(http_server_requests_seconds_sum{method=\"DELETE\"}[1m]))/sum(rate(http_server_requests_seconds_count{method=\"DELETE\"}[1m]))",
       "legendFormat": "POST"
      }
     ]
    }
   ]
  }
 ]
}