apiVersion: v1
kind: Service
metadata:
  name: crud-service
  labels:
    app: crud-service
spec:
  selector:
    app: crud-service
  ports:
    - protocol: TCP
      name: web-traffic
      port: 8000
      targetPort: web
  type: ClusterIP
  